### ISSUE TITLE
Expose new endpoint that runs simple scrape operation on the backend

### ISSUE THREAD

**Issue by mattkindy-praetorian** [mattkindy-praetorian/carmenta#3]
We just want to get something hardcoded working -- 

Would like to add this dependency to the project: https://github.com/joeyism/linkedin_scraper

This is done once I can boot up the application and hit this endpoint and get data in the response

**Comment by praetorian-annapobletts** [comment]
/api/scraper?keyword=Test&num=4 (optional query parameters).
